# Generated by Django 4.1.3 on 2022-12-06 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authwiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='is_loggedin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Auth_library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('functionality', models.CharField(max_length=200)),
                ('code_snippet', models.CharField(max_length=5000)),
                ('comments', models.CharField(max_length=5000)),
                ('categories', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authwiki.users')),
            ],
        ),
    ]
