# Generated by Django 4.1.3 on 2022-12-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authwiki', '0002_users_created_at_users_is_loggedin_auth_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='auth_library',
            old_name='name',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='users',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvote', models.ManyToManyField(related_name='comment_downvote', to='authwiki.comment')),
                ('upvote', models.ManyToManyField(related_name='comment_upvote', to='authwiki.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authwiki.auth_library'),
        ),
    ]
